### ISSUE TITLE
Use `std:function` instead of function pointers for callbacks

### ISSUE THREAD

**Issue by JayKickliter** [msemegen/CML#27]
It gives callee more freedom on what callback data the can use. They could pass in plain old function pointer if desired, or create a function object via a lambda.

**Comment by msemegen** [comment]
I need to make some tests about possible overhead that can std::function make, but in general you are right.

**Comment by JayKickliter** [comment]
> I need to make some tests about possible overhead that can std::function make, but in general you are right.

It depends on how they're created, but good point. In theory they will heap allocate when capturing data, but I know at least GCC has small function optimization and doesn't allocate when capturing less than three `sizeof(void *)` worth of data.
