### ISSUE TITLE
Consider replacing custom collections with Embedded Template Library

### ISSUE THREAD

**Issue by JayKickliter** [msemegen/CML#34]
There are so many edge cases when implementing collections that should handle non-trivial element types. [ETL](https://www.etlcpp.com) is pretty mature and has already done the hard part.

**Comment by msemegen** [comment]
Yes, I'm aware of etl and I think is good idea to use it, instead of custom collections. Additional benefit is support for some standard stl features (type traits etc).

**Comment by msemegen** [comment]
You can use ETL or standard collections. 
All custom collections are removed from CML.
